name: Elixir CI

on:
  push:

env:
  OTP_VERSION: "27.2"
  ELIXIR_VERSION: "1.18.0-otp-27"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get
      - run: mix format --check-formatted

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get
      - run: mix dialyzer

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.0-alpine3.20
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: ecto://postgres:postgres@localhost/timesink_test
      RESEND_API_KEY: "test"
      TIMESINK_TEST_S3_ACCESS_KEY_ID: minioadmin
      TIMESINK_TEST_S3_ACCESS_KEY_SECRET: minioadmin
      AUTH_TOKEN_SALT: "test_salt"


    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-asdf_${{ hashFiles('.tool-versions') }}-mix_${{ hashFiles('**/mix.lock') }}
          path: |
            deps
            $HOME/.asdf

      # Start a MinIO container on :9000
      - run: docker run -d -p 9000:9000 --name minio minio/minio server /data && sleep 5

      # MinIO basic setup
      - run: asdf plugin add mc
      - run: asdf install mc
      - run: sleep 5; mc --debug --insecure config host add minio http://localhost:9000 minioadmin minioadmin
      - run: sleep 1; mc --debug --insecure mb -p minio/timesink-dev

      - run: mix deps.get
      - run: mix compile
      - run: mix do ecto.create + ecto.migrate + run priv/repo/seeds.exs
      - run: mix test
